build:
	docker build --compress -t jodafons/orchestra:base .
	docker build --compress -t jodafons/orchestra:latest .
push:
	docker push jodafons/orchestra:base
	docker push jodafons/orchestra:latest

