build:
	docker build --compress -t jodafons/orchestra:latest .
	docker build --compress -t jodafons/orchestra:cluster .
push:
	docker push jodafons/orchestra:latest
	docker push jodafons/orchestra:cluster

