FROM centos:7

USER root
SHELL ["/bin/bash", "-c"]

RUN yum install -y git python3 python3-pip
RUN pip3 install -U pip
RUN pip3 install wheel
RUN pip3 install --user wheel
RUN pip3 install future
RUN pip3 install --user future
RUN pip3 install email_validator
RUN pip3 install --user email_validator
